AWSTemplateFormatVersion: "2010-09-09"
Description: "Backend: ECR + ECS (Fargate)"

Parameters:
  ProjectName:
    Type: String
    Default: 'three-tier'

  Environment:
    Type: String
    Default: 'dev'

Resources:
  # ECR Repo
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ProjectName}-${Environment}"
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true

  # ECS Cluster
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ProjectName}-${Environment}-cluster"

  # CloudWatch Logs (recommended)
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ProjectName}-${Environment}"
      RetentionInDays: 14

  # Task Execution Role (required for Fargate)
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # Security group for Fargate task ENIs
  TaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${ProjectName}-${Environment} fargate tasks sg"
      VpcId:
        Fn::ImportValue:
          !Sub "${ProjectName}-${Environment}-VpcId"
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0


Outputs:
  EcsClusterArn:
    Value: !GetAtt EcsCluster.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-EcsClusterArn"

  TaskExecutionRoleArn:
    Value: !GetAtt TaskExecutionRole.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-TaskExecutionRoleArn"

  LogGroupName:
    Value: !Ref LogGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-LogGroupName"

  TaskSecurityGroupId:
    Value: !Ref TaskSecurityGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-TaskSecurityGroupId"
